Update patch set 3
Patch Set 3:

Flake8 Violations: 1
First 3 shown
---
 ./tests/unit/test_utils.py:12:1: F811 redefinition of unused 'mock' from line 10
 import mock
 ^

Patch-set: 3