Revert "Optimize list express to list generator"
This reverts commit e5a787046aff97a9925a35874d2b6535a9a41c0c.

Trying to solve [1]

Deploy failed!!!.Traceback (most recent call last):
  File "/home/daisy/deploy/tempest.py", line 94, in prepare_install
    host_interface_map, vip, isbare)
  File "/home/daisy/deploy/tempest.py", line 216, in add_hosts_interface
    add_host_role(cluster_id, host['id'], host_name, host['name'], vip)
  File "/home/daisy/deploy/tempest.py", line 225, in add_host_role
    role.name == "COMPUTER"][0]
IndexError: list index out of range

[1] https://build.opnfv.org/ci/job/daisy-deploy-daily-master/626/consoleFull

Change-Id: I4017b4b38fa350a28d9e9dd5b157caab885a80d0
Signed-off-by: Zhijiang Hu <hu.zhijiang@zte.com.cn>